# Generated by Django 4.2.20 on 2025-04-23 12:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_cartitem_cartitem_unique_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('preparing', 'Tayyorlanmoqda'), ('on_the_way', "Yo'lda"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='new', max_length=20, verbose_name='Holati')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy summa')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Yetkazib berish'), ('pickup', 'Olib ketish')], default='delivery', max_length=10, verbose_name='Yetkazib berish turi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta orqali')], default='cash', max_length=10, verbose_name="To'lov turi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Soni')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birlik narxi (buyurtma paytida)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy narx')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
    ]
