# Generated by Django 4.2.20 on 2025-04-23 16:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Filial nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('avg_preparation_minutes', models.PositiveIntegerField(default=20, help_text="Buyurtma tayyor bo'lishi uchun taxminiy vaqt", verbose_name="O'rtacha tayyorlash vaqti (daqiqa)")),
                ('avg_delivery_extra_minutes', models.PositiveIntegerField(default=15, help_text="Tayyor bo'lgandan keyin yetkazib berish uchun taxminiy qo'shimcha vaqt", verbose_name="O'rtacha yetkazish uchun qo'shimcha vaqt (daqiqa)")),
                ('is_active', models.BooleanField(default=True, help_text='Filial hozirda ishlayaptimi va buyurtma uchun tanlanishi mumkinmi?', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taxminiy yetkazib berish vaqti (delivery)'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Taxminiy tayyor bo'lish vaqti (pickup)"),
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Hafta kuni')),
                ('from_hour', models.TimeField(verbose_name='Dan (vaqt)')),
                ('to_hour', models.TimeField(verbose_name='Gacha (vaqt)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='api.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Ish vaqti',
                'verbose_name_plural': 'Ish vaqtlari',
                'ordering': ['branch', 'weekday', 'from_hour'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_orders', to='api.branch', verbose_name='Olib ketish filiali'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(fields=('branch', 'weekday', 'from_hour'), name='unique_branch_weekday_from_hour'),
        ),
    ]
