# Generated by Django 4.2.20 on 2025-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_branch_order_estimated_delivery_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2, null=True, verbose_name='Til kodi'),
        ),
    ]
