# Generated by Django 4.2.20 on 2025-05-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
    ]
