# Generated by Django 4.2.20 on 2025-05-17 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_otp_code_remove_user_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Masalan, 'Uy', 'Ish', 'Do'stimniki'", max_length=100, null=True, verbose_name='Manzil nomi')),
                ('address_text', models.TextField(blank=True, help_text="Reverse geocodingdan olingan yoki foydalanuvchi kiritgan to'liq manzil", null=True, verbose_name='Matnli manzil')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi manzili',
                'verbose_name_plural': 'Foydalanuvchi manzillari',
                'ordering': ['-created_at'],
            },
        ),
    ]
