# Generated by Django 4.2.20 on 2025-05-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_promotion_promotiontranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'translations__name'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='google_drive_file_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Google Drive Fayl IDsi'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Admin panelidan yuklanadigan vaqtinchalik rasm', null=True, upload_to='categories_local_temp/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_gdrive_url',
            field=models.URLField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Google Drive Rasm URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.category', verbose_name='Asosiy Kategoriya'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(default='temp-slug', help_text="Link uchun unikal nom (faqat lotin harflari, sonlar, chiziqcha va pastki chiziq). Odatda avtomatik to'ldiriladi.", max_length=200, verbose_name='Slug (link uchun)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='google_drive_file_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Admin panelidan yuklanadigan vaqtinchalik rasm', null=True, upload_to='products_local_temp/', verbose_name='Mahalliy Rasm'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_gdrive_url',
            field=models.URLField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Google Drive Rasm URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='google_drive_file_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Google Drive Fayl IDsi'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image_gdrive_url',
            field=models.URLField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Google Drive Rasm URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Mavjudligi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Admin panelidan yuklanadigan vaqtinchalik rasm', null=True, upload_to='promotions_local_temp/', verbose_name='Rasm'),
        ),
    ]
