# Generated by Django 4.2.20 on 2025-05-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
    ]
